export HISTSIZE=50000
export HISTFILESIZE=50000
export HISTCONTROL=ignoreboth:erasedups
shopt -s histappend

if command -v fzf >/dev/null 2>&1; then
  eval "$(fzf --bash)"
fi
if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook bash)"
fi

alias c=cargo
alias nix='nix -L'

PS1='\[\e[38;5;183m\]\h\[\e[38;5;8m\] :: \[\e[38;5;14m\]\w\[\e[33m\] \$ \[\e[0m\]'
