set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g status-style "bg=default"
set -g status-left-length 100
set -g status-right ""
set -g status-left "#S"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g automatic-rename on
set -g mouse on
set -g focus-events off
set -g history-limit 5000
set -g escape-time 500

bind f run-shell "tmux neww tmux-sessioniser"
bind g display-popup -w 85% -h 85% -E lazygit
bind t display-popup -w 75% -h 75% -E bash
bind D detach

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
