HISTSIZE=50000
SAVEHIST=50000
setopt append_history
setopt hist_ignore_all_dups

if command -v fzf >/dev/null 2>&1; then
  eval "$(fzf --zsh)"
fi
if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

alias c=cargo
alias nix='nix -L'
